### ISSUE TITLE
Get familiar with github issue tracker

### ISSUE THREAD

**Issue by gh0s7ik** [gh0s7ik/baraholker#1]
Now that I am ready to push my changes to github, I need to create some tasks and subtasks to facilitate development.

- [ ] read about milestones and releases
- [ ] read about projects
- [ ] read about issues categorization
